using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace _60_Parsecs_Sprite_Generator
{
	internal class CharacterStatuses
	{
		public static readonly Dictionary<String, List<String>> statuses = //словарь состояний персонажей
			new Dictionary<String, List<String>>
			{
				//-Norm
				{"NormalHair0Normal", new List<String>{"NBody", "NFace", "Hair0" } },
				{"NormalHair1Normal", new List<String>{"NBody", "NFace", "Hair1" } },
				{"NormalHair2Normal", new List<String>{"NBody", "NFace", "Hair2" } },
				{"NormalHair3Normal", new List<String>{"NBody", "NFace", "Hair3" } },
				{"NormalHair0Up", new List<String>{"NBody", "NUpFace", "Hair0" } },
				{"NormalHair1Up", new List<String>{"NBody", "NUpFace", "Hair1" } },
				{"NormalHair2Up", new List<String>{"NBody", "NUpFace", "Hair2" } },
				{"NormalHair3Up", new List<String>{"NBody", "NUpFace", "Hair3" } },
				{"NormalHair0Down", new List<String>{"NBody", "NDownFace", "Hair0" } },
				{"NormalHair1Down", new List<String>{"NBody", "NDownFace", "Hair1" } },
				{"NormalHair2Down", new List<String>{"NBody", "NDownFace", "Hair2" } },
				{"NormalHair3Down", new List<String>{"NBody", "NDownFace", "Hair3" } },
				{"NormalHair0NormalSick", new List<String>{"NBody", "NSiFace", "Hair0" } },
				{"NormalHair1NormalSick", new List<String>{"NBody", "NSiFace", "Hair1" } },
				{"NormalHair2NormalSick", new List<String>{"NBody", "NSiFace", "Hair2" } },
				{"NormalHair3NormalSick", new List<String>{"NBody", "NSiFace", "Hair3" } },
				{"NormalHair0UpSick", new List<String>{"NBody", "NSiUpFace", "Hair0" } },
				{"NormalHair1UpSick", new List<String>{"NBody", "NSiUpFace", "Hair1" } },
				{"NormalHair2UpSick", new List<String>{"NBody", "NSiUpFace", "Hair2" } },
				{"NormalHair3UpSick", new List<String>{"NBody", "NSiUpFace", "Hair3" } },
				{"NormalHair0DownSick", new List<String>{"NBody", "NSiDownFace", "Hair0" } },
				{"NormalHair1DownSick", new List<String>{"NBody", "NSiDownFace", "Hair1" } },
				{"NormalHair2DownSick", new List<String>{"NBody", "NSiDownFace", "Hair2" } },
				{"NormalHair3DownSick", new List<String>{"NBody", "NSiDownFace", "Hair3" } },
				{"NormalHair0NormalHurt", new List<String>{"NBody", "NFace", "Hair0", "NHurt" } },
				{"NormalHair1NormalHurt", new List<String>{"NBody", "NFace", "Hair1", "NHurt" } },
				{"NormalHair2NormalHurt", new List<String>{"NBody", "NFace", "Hair2", "NHurt" } },
				{"NormalHair3NormalHurt", new List<String>{"NBody", "NFace", "Hair3", "NHurt" } },
				{"NormalHair0UpHurt", new List<String>{"NBody", "NUpFace", "Hair0", "NHurt" } },
				{"NormalHair1UpHurt", new List<String>{"NBody", "NUpFace", "Hair1", "NHurt" } },
				{"NormalHair2UpHurt", new List<String>{"NBody", "NUpFace", "Hair2", "NHurt" } },
				{"NormalHair3UpHurt", new List<String>{"NBody", "NUpFace", "Hair3", "NHurt" } },
				{"NormalHair0DownHurt", new List<String>{"NBody", "NDownFace", "Hair0", "NHurt" } },
				{"NormalHair2DownHurt", new List<String>{"NBody", "NDownFace", "Hair2", "NHurt" } },
				{"NormalHair1DownHurt", new List<String>{"NBody", "NDownFace", "Hair1", "NHurt" } },
				{"NormalHair3DownHurt", new List<String>{"NBody", "NDownFace", "Hair3", "NHurt" } },
				{"NormalHair0NormalHurtSick", new List<String>{"NBody", "NSiFace", "Hair0", "NHurt" } },
				{"NormalHair1NormalHurtSick", new List<String>{"NBody", "NSiFace", "Hair1", "NHurt" } },
				{"NormalHair2NormalHurtSick", new List<String>{"NBody", "NSiFace", "Hair2", "NHurt" } },
				{"NormalHair3NormalHurtSick", new List<String>{"NBody", "NSiFace", "Hair3", "NHurt" } },
				{"NormalHair0UpHurtSick", new List<String>{"NBody", "NSiUpFace", "Hair0", "NHurt" } },
				{"NormalHair1UpHurtSick", new List<String>{"NBody", "NSiUpFace", "Hair1", "NHurt" } },
				{"NormalHair2UpHurtSick", new List<String>{"NBody", "NSiUpFace", "Hair2", "NHurt" } },
				{"NormalHair3UpHurtSick", new List<String>{"NBody", "NSiUpFace", "Hair3", "NHurt" } },
				{"NormalHair0DownHurtSick", new List<String>{"NBody", "NSiDownFace", "Hair0", "NHurt" } },
				{"NormalHair1DownHurtSick", new List<String>{"NBody", "NSiDownFace", "Hair1", "NHurt" } },
				{"NormalHair2DownHurtSick", new List<String>{"NBody", "NSiDownFace", "Hair2", "NHurt" } },
				{"NormalHair3DownHurtSick", new List<String>{"NBody", "NSiDownFace", "Hair3", "NHurt" } },
				//-Starving
				{"StarvingHair0Normal", new List<String>{"StBody", "StFace", "StHair0" } },
				{"StarvingHair1Normal", new List<String>{"StBody", "StFace", "StHair1" } },
				{"StarvingHair2Normal", new List<String>{"StBody", "StFace", "StHair2" } },
				{"StarvingHair3Normal", new List<String>{"StBody", "StFace", "StHair3" } },
				{"StarvingHair0Up", new List<String>{"StBody", "StUpFace", "StHair0" } },
				{"StarvingHair1Up", new List<String>{"StBody", "StUpFace", "StHair1" } },
				{"StarvingHair2Up", new List<String>{"StBody", "StUpFace", "StHair2" } },
				{"StarvingHair3Up", new List<String>{"StBody", "StUpFace", "StHair3" } },
				{"StarvingHair0Down", new List<String>{"StBody", "StDownFace", "StHair0" } },
				{"StarvingHair1Down", new List<String>{"StBody", "StDownFace", "StHair1" } },
				{"StarvingHair2Down", new List<String>{"StBody", "StDownFace", "StHair2" } },
				{"StarvingHair3Down", new List<String>{"StBody", "StDownFace", "StHair3" } },
				{"StarvingHair0NormalSick", new List<String>{"StBody", "StSiFace", "StHair0" } },
				{"StarvingHair1NormalSick", new List<String>{"StBody", "StSiFace", "StHair1" } },
				{"StarvingHair2NormalSick", new List<String>{"StBody", "StSiFace", "StHair2" } },
				{"StarvingHair3NormalSick", new List<String>{"StBody", "StSiFace", "StHair3" } },
				{"StarvingHair0UpSick", new List<String>{"StBody", "StSiUpFace", "StHair0" } },
				{"StarvingHair1UpSick", new List<String>{"StBody", "StSiUpFace", "StHair1" } },
				{"StarvingHair2UpSick", new List<String>{"StBody", "StSiUpFace", "StHair2" } },
				{"StarvingHair3UpSick", new List<String>{"StBody", "StSiUpFace", "StHair3" } },
				{"StarvingHair0DownSick", new List<String>{"StBody", "StSiDownFace", "StHair0" } },
				{"StarvingHair1DownSick", new List<String>{"StBody", "StSiDownFace", "StHair1" } },
				{"StarvingHair2DownSick", new List<String>{"StBody", "StSiDownFace", "StHair2" } },
				{"StarvingHair3DownSick", new List<String>{"StBody", "StSiDownFace", "StHair3" } },
				{"StarvingHair0NormalHurt", new List<String>{"StBody", "StFace", "StHair0", "StHurt" } },
				{"StarvingHair1NormalHurt", new List<String>{"StBody", "StFace", "StHair1", "StHurt" } },
				{"StarvingHair2NormalHurt", new List<String>{"StBody", "StFace", "StHair2", "StHurt" } },
				{"StarvingHair3NormalHurt", new List<String>{"StBody", "StFace", "StHair3", "StHurt" } },
				{"StarvingHair0UpHurt", new List<String>{"StBody", "StUpFace", "StHair0", "StHurt" } },
				{"StarvingHair1UpHurt", new List<String>{"StBody", "StUpFace", "StHair1", "StHurt" } },
				{"StarvingHair2UpHurt", new List<String>{"StBody", "StUpFace", "StHair2", "StHurt" } },
				{"StarvingHair3UpHurt", new List<String>{"StBody", "StUpFace", "StHair3", "StHurt" } },
				{"StarvingHair0DownHurt", new List<String>{"StBody", "StDownFace", "StHair0", "StHurt" } },
				{"StarvingHair1DownHurt", new List<String>{"StBody", "StDownFace", "StHair1", "StHurt" } },
				{"StarvingHair2DownHurt", new List<String>{"StBody", "StDownFace", "StHair2", "StHurt" } },
				{"StarvingHair3DownHurt", new List<String>{"StBody", "StDownFace", "StHair3", "StHurt" } },
				{"StarvingHair0NormalHurtSick", new List<String>{"StBody", "StSiFace", "StHair0", "StHurt" } },
				{"StarvingHair1NormalHurtSick", new List<String>{"StBody", "StSiFace", "StHair1", "StHurt" } },
				{"StarvingHair2NormalHurtSick", new List<String>{"StBody", "StSiFace", "StHair2", "StHurt" } },
				{"StarvingHair3NormalHurtSick", new List<String>{"StBody", "StSiFace", "StHair3", "StHurt" } },
				{"StarvingHair0UpHurtSick", new List<String>{"StBody", "StSiUpFace", "StHair0", "StHurt" } },
				{"StarvingHair1UpHurtSick", new List<String>{"StBody", "StSiUpFace", "StHair1", "StHurt" } },
				{"StarvingHair2UpHurtSick", new List<String>{"StBody", "StSiUpFace", "StHair2", "StHurt" } },
				{"StarvingHair3UpHurtSick", new List<String>{"StBody", "StSiUpFace", "StHair3", "StHurt" } },
				{"StarvingHair0DownHurtSick", new List<String>{"StBody", "StSiDownFace", "StHair0", "StHurt" } },
				{"StarvingHair1DownHurtSick", new List<String>{"StBody", "StSiDownFace", "StHair1", "StHurt" } },
				{"StarvingHair2DownHurtSick", new List<String>{"StBody", "StSiDownFace", "StHair2", "StHurt" } },
				{"StarvingHair3DownHurtSick", new List<String>{"StBody", "StSiDownFace", "StHair3", "StHurt" } },
				//-WFed
				{"WellFedHair0Normal", new List<String>{"WFBody", "WFFace", "WFHair0" } },
				{"WellFedHair1Normal", new List<String>{"WFBody", "WFFace", "WFHair1" } },
				{"WellFedHair2Normal", new List<String>{"WFBody", "WFFace", "WFHair2" } },
				{"WellFedHair3Normal", new List<String>{"WFBody", "WFFace", "WFHair3" } },
				{"WellFedHair0Up", new List<String>{"WFBody", "WFUpFace", "WFHair0" } },
				{"WellFedHair1Up", new List<String>{"WFBody", "WFUpFace", "WFHair1" } },
				{"WellFedHair2Up", new List<String>{"WFBody", "WFUpFace", "WFHair2" } },
				{"WellFedHair3Up", new List<String>{"WFBody", "WFUpFace", "WFHair3" } },
				{"WellFedHair0Down", new List<String>{"WFBody", "WFDownFace", "WFHair0" } },
				{"WellFedHair1Down", new List<String>{"WFBody", "WFDownFace", "WFHair1" } },
				{"WellFedHair2Down", new List<String>{"WFBody", "WFDownFace", "WFHair2" } },
				{"WellFedHair3Down", new List<String>{"WFBody", "WFDownFace", "WFHair3" } },
				{"WellFedHair0NormalSick", new List<String>{"WFBody", "WFSiFace", "WFHair0" } },
				{"WellFedHair1NormalSick", new List<String>{"WFBody", "WFSiFace", "WFHair1" } },
				{"WellFedHair2NormalSick", new List<String>{"WFBody", "WFSiFace", "WFHair2" } },
				{"WellFedHair3NormalSick", new List<String>{"WFBody", "WFSiFace", "WFHair3" } },
				{"WellFedHair0UpSick", new List<String>{"WFBody", "WFSiUpFace", "WFHair0" } },
				{"WellFedHair1UpSick", new List<String>{"WFBody", "WFSiUpFace", "WFHair1" } },
				{"WellFedHair2UpSick", new List<String>{"WFBody", "WFSiUpFace", "WFHair2" } },
				{"WellFedHair3UpSick", new List<String>{"WFBody", "WFSiUpFace", "WFHair3" } },
				{"WellFedHair0DownSick", new List<String>{"WFBody", "WFSiDownFace", "WFHair0" } },
				{"WellFedHair1DownSick", new List<String>{"WFBody", "WFSiDownFace", "WFHair1" } },
				{"WellFedHair2DownSick", new List<String>{"WFBody", "WFSiDownFace", "WFHair2" } },
				{"WellFedHair3DownSick", new List<String>{"WFBody", "WFSiDownFace", "WFHair3" } },
				{"WellFedHair0NormalHurt", new List<String>{"WFBody", "WFFace", "WFHair0", "WFHurt" } },
				{"WellFedHair1NormalHurt", new List<String>{"WFBody", "WFFace", "WFHair1", "WFHurt"  } },
				{"WellFedHair2NormalHurt", new List<String>{"WFBody", "WFFace", "WFHair2", "WFHurt"  } },
				{"WellFedHair3NormalHurt", new List<String>{"WFBody", "WFFace", "WFHair3", "WFHurt"  } },
				{"WellFedHair0UpHurt", new List<String>{"WFBody", "WFUpFace", "WFHair0", "WFHurt"  } },
				{"WellFedHair1UpHurt", new List<String>{"WFBody", "WFUpFace", "WFHair1", "WFHurt"  } },
				{"WellFedHair2UpHurt", new List<String>{"WFBody", "WFUpFace", "WFHair2", "WFHurt"  } },
				{"WellFedHair3UpHurt", new List<String>{"WFBody", "WFUpFace", "WFHair3", "WFHurt" } },
				{"WellFedHair0DownHurt", new List<String>{"WFBody", "WFDownFace", "WFHair0", "WFHurt"  } },
				{"WellFedHair1DownHurt", new List<String>{"WFBody", "WFDownFace", "WFHair1", "WFHurt"  } },
				{"WellFedHair2DownHurt", new List<String>{"WFBody", "WFDownFace", "WFHair2", "WFHurt"  } },
				{"WellFedHair3DownHurt", new List<String>{"WFBody", "WFDownFace", "WFHair3", "WFHurt" } },
				{"WellFedHair0NormalHurtSick", new List<String>{"WFBody", "WFSiFace", "WFHair0", "WFHurt"  } },
				{"WellFedHair1NormalHurtSick", new List<String>{"WFBody", "WFSiFace", "WFHair1", "WFHurt"  } },
				{"WellFedHair2NormalHurtSick", new List<String>{"WFBody", "WFSiFace", "WFHair2", "WFHurt"  } },
				{"WellFedHair3NormalHurtSick", new List<String>{"WFBody", "WFSiFace", "WFHair3", "WFHurt" } },
				{"WellFedHair0UpHurtSick", new List<String>{"WFBody", "WFSiUpFace", "WFHair0", "WFHurt"  } },
				{"WellFedHair1UpHurtSick", new List<String>{"WFBody", "WFSiUpFace", "WFHair1", "WFHurt"  } },
				{"WellFedHair2UpHurtSick", new List<String>{"WFBody", "WFSiUpFace", "WFHair2", "WFHurt"  } },
				{"WellFedHair3UpHurtSick", new List<String>{"WFBody", "WFSiUpFace", "WFHair3", "WFHurt" } },
				{"WellFedHair0DownHurtSick", new List<String>{"WFBody", "WFSiDownFace", "WFHair0", "WFHurt"  } },
				{"WellFedHair1DownHurtSick", new List<String>{"WFBody", "WFSiDownFace", "WFHair1", "WFHurt"  } },
				{"WellFedHair2DownHurtSick", new List<String>{"WFBody", "WFSiDownFace", "WFHair2", "WFHurt"  } },
				{"WellFedHair3DownHurtSick", new List<String>{"WFBody", "WFSiDownFace", "WFHair3", "WFHurt" } },
				//Hero
				{"NormalHair0NormalHero", new List<String>{"HBody", "HFace", "HHair0" } },
				{"NormalHair1NormalHero", new List<String>{"HBody", "HFace", "HHair1" } },
				{"NormalHair2NormalHero", new List<String>{"HBody", "HFace", "HHair2" } },
				{"NormalHair3NormalHero", new List<String>{"HBody", "HFace", "HHair3" } },
				{"NormalHair0UpHero", new List<String>{"HBody", "HUpFace", "HHair0" } },
				{"NormalHair1UpHero", new List<String>{"HBody", "HUpFace", "HHair1" } },
				{"NormalHair2UpHero", new List<String>{"HBody", "HUpFace", "HHair2" } },
				{"NormalHair3UpHero", new List<String>{"HBody", "HUpFace", "HHair3" } },
				{"NormalHair0DownHero", new List<String>{"HBody", "HDownFace", "HHair0" } },
				{"NormalHair1DownHero", new List<String>{"HBody", "HDownFace", "HHair1" } },
				{"NormalHair2DownHero", new List<String>{"HBody", "HDownFace", "HHair2" } },
				{"NormalHair3DownHero", new List<String>{"HBody", "HDownFace", "HHair3" } },
				{"NormalHair0NormalHurtHero", new List<String>{"HBody", "HFace", "HHair0", "HHurt" } },
				{"NormalHair1NormalHurtHero", new List<String>{"HBody", "HFace", "HHair1", "HHurt" } },
				{"NormalHair2NormalHurtHero", new List<String>{"HBody", "HFace", "HHair2", "HHurt" } },
				{"NormalHair3NormalHurtHero", new List<String>{"HBody", "HFace", "HHair3", "HHurt" } },
				{"NormalHair0UpHurtHero", new List<String>{"HBody", "HUpFace", "HHair0", "HHurt" } },
				{"NormalHair1UpHurtHero", new List<String>{"HBody", "HUpFace", "HHair1", "HHurt" } },
				{"NormalHair2UpHurtHero", new List<String>{"HBody", "HUpFace", "HHair2", "HHurt" } },
				{"NormalHair3UpHurtHero", new List<String>{"HBody", "HUpFace", "HHair3", "HHurt" } },
				{"NormalHair0DownHurtHero", new List<String>{"HBody", "HDownFace", "HHair0", "HHurt" } },
				{"NormalHair1DownHurtHero", new List<String>{"HBody", "HDownFace", "HHair1", "HHurt" } },
				{"NormalHair2DownHurtHero", new List<String>{"HBody", "HDownFace", "HHair2", "HHurt" } },
				{"NormalHair3DownHurtHero", new List<String>{"HBody", "HDownFace", "HHair3", "HHurt" } },
				//StarvHero
				{"StarvingHair0NormalHero", new List<String>{"HStBody", "HStFace", "HStHair0" } },
				{"StarvingHair1NormalHero", new List<String>{"HStBody", "HStFace", "HStHair1" } },
				{"StarvingHair2NormalHero", new List<String>{"HStBody", "HStFace", "HStHair2" } },
				{"StarvingHair3NormalHero", new List<String>{"HStBody", "HStFace", "HStHair3" } },
				{"StarvingHair0UpHero", new List<String>{"HStBody", "HStUpFace", "HStHair0" } },
				{"StarvingHair1UpHero", new List<String>{"HStBody", "HStUpFace", "HStHair1" } },
				{"StarvingHair2UpHero", new List<String>{"HStBody", "HStUpFace", "HStHair2" } },
				{"StarvingHair3UpHero", new List<String>{"HStBody", "HStUpFace", "HStHair3" } },
				{"StarvingHair0DownHero", new List<String>{"HStBody", "HStDownFace", "HStHair0" } },
				{"StarvingHair1DownHero", new List<String>{"HStBody", "HStDownFace", "HStHair1" } },
				{"StarvingHair2DownHero", new List<String>{"HStBody", "HStDownFace", "HStHair2" } },
				{"StarvingHair3DownHero", new List<String>{"HStBody", "HStDownFace", "HStHair3" } },
				{"StarvingHair0NormalHurtHero", new List<String>{"HStBody", "HStFace", "HStHair0", "HStHurt" } },
				{"StarvingHair1NormalHurtHero", new List<String>{"HStBody", "HStFace", "HStHair1", "HStHurt" } },
				{"StarvingHair2NormalHurtHero", new List<String>{ "HStBody", "HStFace", "HStHair2", "HStHurt" } },
				{"StarvingHair3NormalHurtHero", new List<String>{ "HStBody", "HStFace", "HStHair3", "HStHurt" } },
				{"StarvingHair0UpHurtHero", new List<String>{"HStBody", "HStUpFace", "HStHair0", "HStHurt" } },
				{"StarvingHair1UpHurtHero", new List<String>{ "HStBody", "HStUpFace", "HStHair1", "HStHurt" } },
				{"StarvingHair2UpHurtHero", new List<String>{ "HStBody", "HStUpFace", "HStHair2", "HStHurt" } },
				{"StarvingHair3UpHurtHero", new List<String>{ "HStBody", "HStUpFace", "HStHair3", "HStHurt" } },
				{"StarvingHair0DownHurtHero", new List<String>{ "HStBody", "HStDownFace", "HStHair0", "HStHurt" } },
				{"StarvingHair1DownHurtHero", new List<String>{ "HStBody", "HStDownFace", "HStHair1", "HStHurt" } },
				{"StarvingHair2DownHurtHero", new List<String>{ "HStBody", "HStDownFace", "HStHair2", "HStHurt" } },
				{"StarvingHair3DownHurtHero", new List<String>{ "HStBody", "HStDownFace", "HStHair3", "HStHurt" } },
				//WellFedHero
				{"WellFedHair0NormalHero", new List<String>{"WFHBody", "WFHFace", "WFHHair0" } },
				{"WellFedHair1NormalHero", new List<String>{"WFHBody", "WFHFace", "WFHHair1" } },
				{"WellFedHair2NormalHero", new List<String>{"WFHBody", "WFHFace", "WFHHair2" } },
				{"WellFedHair3NormalHero", new List<String>{"WFHBody", "WFHFace", "WFHHair3" } },
				{"WellFedHair0UpHero", new List<String>{"WFHBody", "WFHUpFace", "WFHHair0" } },
				{"WellFedHair1UpHero", new List<String>{"WFHBody", "WFHUpFace", "WFHHair1" } },
				{"WellFedHair2UpHero", new List<String>{"WFHBody", "WFHUpFace", "WFHHair2" } },
				{"WellFedHair3UpHero", new List<String>{"WFHBody", "WFHUpFace", "WFHHair3" } },
				{"WellFedHair0DownHero", new List<String>{"WFHBody", "WFHDownFace", "WFHHair0" } },
				{"WellFedHair1DownHero", new List<String>{"WFHBody", "WFHDownFace", "WFHHair1" } },
				{"WellFedHair2DownHero", new List<String>{"WFHBody", "WFHDownFace", "WFHHair2" } },
				{"WellFedHair3DownHero", new List<String>{"WFHBody", "WFHDownFace", "WFHHair3" } },
				{"WellFedHair0NormalHurtHero", new List<String>{"WFHBody", "WFHFace", "WFHHair0", "WFHHurt" } },
				{"WellFedHair1NormalHurtHero", new List<String>{"WFHBody", "WFHFace", "WFHHair1", "WFHHurt" } },
				{"WellFedHair2NormalHurtHero", new List<String>{"WFHBody", "WFHFace", "WFHHair2", "WFHHurt" } },
				{"WellFedHair3NormalHurtHero", new List<String>{"WFHBody", "WFHFace", "WFHHair3", "WFHHurt" } },
				{"WellFedHair0UpHurtHero", new List<String>{"WFHBody", "WFHUpFace", "WFHHair0", "WFHHurt" } },
				{"WellFedHair1UpHurtHero", new List<String>{"WFHBody", "WFHUpFace", "WFHHair1", "WFHHurt" } },
				{"WellFedHair2UpHurtHero", new List<String>{"WFHBody", "WFHUpFace", "WFHHair2", "WFHHurt" } },
				{"WellFedHair3UpHurtHero", new List<String>{"WFHBody", "WFHUpFace", "WFHHair3", "WFHHurt" } },
				{"WellFedHair0DownHurtHero", new List<String>{ "WFHBody", "WFHDownFace", "WFHHair0", "WFHHurt" } },
				{"WellFedHair1DownHurtHero", new List<String>{ "WFHBody", "WFHDownFace", "WFHHair1", "WFHHurt" } },
				{"WellFedHair2DownHurtHero", new List<String>{ "WFHBody", "WFHDownFace", "WFHHair2", "WFHHurt" } },
				{"WellFedHair3DownHurtHero", new List<String>{ "WFHBody", "WFHDownFace", "WFHHair3", "WFHHurt" } },
				//-Weak
				{"NormalHair0NormalWeak", new List<String>{"WkBody", "WkFace", "WkHair0" } },
				{"NormalHair1NormalWeak", new List<String>{"WkBody", "WkFace", "WkHair1" } },
				{"NormalHair2NormalWeak", new List<String>{"WkBody", "WkFace", "WkHair2" } },
				{"NormalHair3NormalWeak", new List<String>{"WkBody", "WkFace", "WkHair3" } },
				{"NormalHair0UpWeak", new List<String>{"WkBody", "WkUpFace", "WkHair0" } },
				{"NormalHair1UpWeak", new List<String>{"WkBody", "WkUpFace", "WkHair1" } },
				{"NormalHair2UpWeak", new List<String>{"WkBody", "WkUpFace", "WkHair2" } },
				{"NormalHair3UpWeak", new List<String>{"WkBody", "WkUpFace", "WkHair3" } },
				{"NormalHair0DownWeak", new List<String>{"WkBody", "WkDownFace", "WkHair0" } },
				{"NormalHair1DownWeak", new List<String>{"WkBody", "WkDownFace", "WkHair1" } },
				{"NormalHair2DownWeak", new List<String>{"WkBody", "WkDownFace", "WkHair2" } },
				{"NormalHair3DownWeak", new List<String>{"WkBody", "WkDownFace", "WkHair3" } },
				{"NormalHair0NormalSickWeak", new List<String>{"WkBody", "WkSiFace", "WkHair0" } },
				{"NormalHair1NormalSickWeak", new List<String>{"WkBody", "WkSiFace", "WkHair1" } },
				{"NormalHair2NormalSickWeak", new List<String>{"WkBody", "WkSiFace", "WkHair2" } },
				{"NormalHair3NormalSickWeak", new List<String>{"WkBody", "WkSiFace", "WkHair3" } },
				{"NormalHair0UpSickWeak", new List<String>{"WkBody", "WkSiUpFace", "WkHair0" } },
				{"NormalHair1UpSickWeak", new List<String>{"WkBody", "WkSiUpFace", "WkHair1" } },
				{"NormalHair2UpSickWeak", new List<String>{"WkBody", "WkSiUpFace", "WkHair2" } },
				{"NormalHair3UpSickWeak", new List<String>{"WkBody", "WkSiUpFace", "WkHair3" } },
				{"NormalHair0DownSickWeak", new List<String>{"WkBody", "WkSiDownFace", "WkHair0" } },
				{"NormalHair1DownSickWeak", new List<String>{"WkBody", "WkSiDownFace", "WkHair1" } },
				{"NormalHair2DownSickWeak", new List<String>{"WkBody", "WkSiDownFace", "WkHair2" } },
				{"NormalHair3DownSickWeak", new List<String>{"WkBody", "WkSiDownFace", "WkHair3" } },
				{"NormalHair0NormalHurtWeak", new List<String>{"WkBody", "WkFace", "WkHair0", "WkHurt" } },
				{"NormalHair1NormalHurtWeak", new List<String>{"WkBody", "WkFace", "WkHair1", "WkHurt"  } },
				{"NormalHair2NormalHurtWeak", new List<String>{"WkBody", "WkFace", "WkHair2", "WkHurt"  } },
				{"NormalHair3NormalHurtWeak", new List<String>{"WkBody", "WkFace", "WkHair3", "WkHurt"  } },
				{"NormalHair0UpHurtWeak", new List<String>{"WkBody", "WkUpFace", "WkHair0","WkHurt" } },
				{"NormalHair1UpHurtWeak", new List<String>{"WkBody", "WkUpFace", "WkHair1","WkHurt" } },
				{"NormalHair2UpHurtWeak", new List<String>{"WkBody", "WkUpFace", "WkHair2","WkHurt" } },
				{"NormalHair3UpHurtWeak", new List<String>{"WkBody", "WkUpFace", "WkHair3", "WkHurt" } },
				{"NormalHair0DownHurtWeak", new List<String>{"WkBody", "WkDownFace", "WkHair0", "WkHurt"  } },
				{"NormalHair1DownHurtWeak", new List<String>{"WkBody", "WkDownFace", "WkHair1", "WkHurt"  } },
				{"NormalHair2DownHurtWeak", new List<String>{"WkBody", "WkDownFace", "WkHair2", "WkHurt"  } },
				{"NormalHair3DownHurtWeak", new List<String>{"WkBody", "WkDownFace", "WkHair3", "WkHurt" } },
				{"NormalHair0NormalHurtSickWeak", new List<String>{"WkBody", "WkSiFace", "WkHair0", "WkHurt" } },
				{"NormalHair1NormalHurtSickWeak", new List<String>{"WkBody", "WkSiFace", "WkHair1", "WkHurt"  } },
				{"NormalHair2NormalHurtSickWeak", new List<String>{"WkBody", "WkSiFace", "WkHair2", "WkHurt"  } },
				{"NormalHair3NormalHurtSickWeak", new List<String>{"WkBody", "WkSiFace", "WkHair3", "WkHurt"  } },
				{"NormalHair0UpHurtSickWeak", new List<String>{"WkBody", "WkSiUpFace", "WkHair0", "WkHurt"  } },
				{"NormalHair1UpHurtSickWeak", new List<String>{"WkBody", "WkSiUpFace", "WkHair1", "WkHurt"  } },
				{"NormalHair2UpHurtSickWeak", new List<String>{"WkBody", "WkSiUpFace", "WkHair2", "WkHurt"  } },
				{"NormalHair3UpHurtSickWeak", new List<String>{"WkBody", "WkSiUpFace", "WkHair3", "WkHurt" } },
				{"NormalHair0DownHurtSickWeak", new List<String>{"WkBody", "WkSiDownFace", "WkHair0", "WkHurt" } },
				{"NormalHair1DownHurtSickWeak", new List<String>{"WkBody", "WkSiDownFace", "WkHair1", "WkHurt"  } },
				{"NormalHair2DownHurtSickWeak", new List<String>{"WkBody", "WkSiDownFace", "WkHair2", "WkHurt"  } },
				{"NormalHair3DownHurtSickWeak", new List<String>{"WkBody", "WkSiDownFace", "WkHair3", "WkHurt"  } },
				//-WellFed Weak
				{"WellFedHair0NormalWeak", new List<String>{"WFWkBody", "WFWkFace", "WFWkHair0" } },
				{"WellFedHair1NormalWeak", new List<String>{"WFWkBody", "WFWkFace", "WFWkHair1" } },
				{"WellFedHair2NormalWeak", new List<String>{"WFWkBody", "WFWkFace", "WFWkHair2" } },
				{"WellFedHair3NormalWeak", new List<String>{"WFWkBody", "WFWkFace", "WFWkHair3" } },
				{"WellFedHair0UpWeak", new List<String>{"WFWkBody", "WFWkUpFace", "WFWkHair0" } },
				{"WellFedHair1UpWeak", new List<String>{"WFWkBody", "WFWkUpFace", "WFWkHair1" } },
				{"WellFedHair2UpWeak", new List<String>{"WFWkBody", "WFWkUpFace", "WFWkHair2" } },
				{"WellFedHair3UpWeak", new List<String>{"WFWkBody", "WFWkUpFace", "WFWkHair3" } },
				{"WellFedHair0DownWeak", new List<String>{"WFWkBody", "WFWkDownFace", "WFWkHair0" } },
				{"WellFedHair1DownWeak", new List<String>{"WFWkBody", "WFWkDownFace", "WFWkHair1" } },
				{"WellFedHair2DownWeak", new List<String>{"WFWkBody", "WFWkDownFace", "WFWkHair2" } },
				{"WellFedHair3DownWeak", new List<String>{"WFWkBody", "WFWkDownFace", "WFWkHair3" } },
				{"WellFedHair0NormalSickWeak", new List<String>{"WFWkBody", "WFWkSiFace", "WFWkHair0" } },
				{"WellFedHair1NormalSickWeak", new List<String>{"WFWkBody", "WFWkSiFace", "WFWkHair1" } },
				{"WellFedHair2NormalSickWeak", new List<String>{"WFWkBody", "WFWkSiFace", "WFWkHair2" } },
				{"WellFedHair3NormalSickWeak", new List<String>{"WFWkBody", "WFWkSiFace", "WFWkHair3" } },
				{"WellFedHair0UpSickWeak", new List<String>{"WFWkBody", "WFWkSiUpFace", "WFWkHair0" } },
				{"WellFedHair1UpSickWeak", new List<String>{"WFWkBody", "WFWkSiUpFace", "WFWkHair1" } },
				{"WellFedHair2UpSickWeak", new List<String>{"WFWkBody", "WFWkSiUpFace", "WFWkHair2" } },
				{"WellFedHair3UpSickWeak", new List<String>{"WFWkBody", "WFWkSiUpFace", "WFWkHair3" } },
				{"WellFedHair0DownSickWeak", new List<String>{"WFWkBody", "WFWkSiDownFace", "WFWkHair0" } },
				{"WellFedHair1DownSickWeak", new List<String>{"WFWkBody", "WFWkSiDownFace", "WFWkHair1" } },
				{"WellFedHair2DownSickWeak", new List<String>{"WFWkBody", "WFWkSiDownFace", "WFWkHair2" } },
				{"WellFedHair3DownSickWeak", new List<String>{"WFWkBody", "WFWkSiDownFace", "WFWkHair3" } },
				{"WellFedHair0NormalHurtWeak", new List<String>{"WFWkBody", "WFWkFace", "WFWkHair0", "WFWkHurt" } },
				{"WellFedHair1NormalHurtWeak", new List<String>{"WFWkBody", "WFWkFace", "WFWkHair1", "WFWkHurt"  } },
				{"WellFedHair2NormalHurtWeak", new List<String>{"WFWkBody", "WFWkFace", "WFWkHair2", "WFWkHurt"  } },
				{"WellFedHair3NormalHurtWeak", new List<String>{"WFWkBody", "WFWkFace", "WFWkHair3", "WFWkHurt" } },
				{"WellFedHair0UpHurtWeak", new List<String>{"WFWkBody", "WFWkUpFace", "WFWkHair0","WFWkHurt" } },
				{"WellFedHair1UpHurtWeak", new List<String>{"WFWkBody", "WFWkUpFace", "WFWkHair1","WFWkHurt" } },
				{"WellFedHair2UpHurtWeak", new List<String>{"WFWkBody", "WFWkUpFace", "WFWkHair2","WFWkHurt" } },
				{"WellFedHair3UpHurtWeak", new List<String>{"WFWkBody", "WFWkUpFace", "WFWkHair3","WFWkHurt" } },
				{"WellFedHair0DownHurtWeak", new List<String>{"WFWkBody", "WFWkDownFace", "WFWkHair0", "WFWkHurt"  } },
				{"WellFedHair1DownHurtWeak", new List<String>{"WFWkBody", "WFWkDownFace", "WFWkHair1", "WFWkHurt"  } },
				{"WellFedHair2DownHurtWeak", new List<String>{"WFWkBody", "WFWkDownFace", "WFWkHair2", "WFWkHurt"  } },
				{"WellFedHair3DownHurtWeak", new List<String>{"WFWkBody", "WFWkDownFace", "WFWkHair3", "WFWkHurt" } },
				{"WellFedHair0NormalHurtSickWeak", new List<String>{"WFWkBody", "WFWkSiFace", "WFWkHair0", "WFWkHurt" } },
				{"WellFedHair1NormalHurtSickWeak", new List<String>{"WFWkBody", "WFWkSiFace", "WFWkHair1", "WFWkHurt"  } },
				{"WellFedHair2NormalHurtSickWeak", new List<String>{"WFWkBody", "WFWkSiFace", "WFWkHair2", "WFWkHurt"  } },
				{"WellFedHair3NormalHurtSickWeak", new List<String>{"WFWkBody", "WFWkSiFace", "WFWkHair3", "WFWkHurt" } },
				{"WellFedHair0UpHurtSickWeak", new List<String>{"WFWkBody", "WFWkSiUpFace", "WFWkHair0", "WFWkHurt"  } },
				{"WellFedHair1UpHurtSickWeak", new List<String>{"WFWkBody", "WFWkSiUpFace", "WFWkHair1", "WFWkHurt"  } },
				{"WellFedHair2UpHurtSickWeak", new List<String>{"WFWkBody", "WFWkSiUpFace", "WFWkHair2", "WFWkHurt"  } },
				{"WellFedHair3UpHurtSickWeak", new List<String>{"WFWkBody", "WFWkSiUpFace", "WFWkHair3", "WFWkHurt" } },
				{"WellFedHair0DownHurtSickWeak", new List<String>{"WFWkBody", "WFWkSiDownFace", "WFWkHair0", "WFWkHurt" } },
				{"WellFedHair1DownHurtSickWeak", new List<String>{"WFWkBody", "WFWkSiDownFace", "WFWkHair1", "WFWkHurt"  } },
				{"WellFedHair2DownHurtSickWeak", new List<String>{"WFWkBody", "WFWkSiDownFace", "WFWkHair2", "WFWkHurt"  } },
				{"WellFedHair3DownHurtSickWeak", new List<String>{"WFWkBody", "WFWkSiDownFace", "WFWkHair3", "WFWkHurt" } },
				//-Starving Weak
				{"StarvingHair0NormalWeak", new List<String>{"WkStBody", "WkStFace", "WkStHair0" } },
				{"StarvingHair1NormalWeak", new List<String>{"WkStBody", "WkStFace", "WkStHair1" } },
				{"StarvingHair2NormalWeak", new List<String>{"WkStBody", "WkStFace", "WkStHair2" } },
				{"StarvingHair3NormalWeak", new List<String>{"WkStBody", "WkStFace", "WkStHair3" } },
				{"StarvingHair0UpWeak", new List<String>{"WkStBody", "WkStUpFace", "WkStHair0" } },
				{"StarvingHair1UpWeak", new List<String>{"WkStBody", "WkStUpFace", "WkStHair1" } },
				{"StarvingHair2UpWeak", new List<String>{"WkStBody", "WkStUpFace", "WkStHair2" } },
				{"StarvingHair3UpWeak", new List<String>{"WkStBody", "WkStUpFace", "WkStHair3" } },
				{"StarvingHair0DownWeak", new List<String>{"WkStBody", "WkStDownFace", "WkStHair0" } },
				{"StarvingHair1DownWeak", new List<String>{"WkStBody", "WkStDownFace", "WkStHair1" } },
				{"StarvingHair2DownWeak", new List<String>{"WkStBody", "WkStDownFace", "WkStHair2" } },
				{"StarvingHair3DownWeak", new List<String>{"WkStBody", "WkStDownFace", "WkStHair3" } },
				{"StarvingHair0NormalSickWeak", new List<String>{"WkStBody", "WkStSiFace", "WkStHair0" } },
				{"StarvingHair1NormalSickWeak", new List<String>{"WkStBody", "WkStSiFace", "WkStHair1" } },
				{"StarvingHair2NormalSickWeak", new List<String>{"WkStBody", "WkStSiFace", "WkStHair2" } },
				{"StarvingHair3NormalSickWeak", new List<String>{"WkStBody", "WkStSiFace", "WkStHair3" } },
				{"StarvingHair0UpSickWeak", new List<String>{"WkStBody", "WkStSiUpFace", "WkStHair0" } },
				{"StarvingHair1UpSickWeak", new List<String>{"WkStBody", "WkStSiUpFace", "WkStHair1" } },
				{"StarvingHair2UpSickWeak", new List<String>{"WkStBody", "WkStSiUpFace", "WkStHair2" } },
				{"StarvingHair3UpSickWeak", new List<String>{"WkStBody", "WkStSiUpFace", "WkStHair3" } },
				{"StarvingHair0DownSickWeak", new List<String>{"WkStBody", "WkStSiDownFace", "WkStHair0" } },
				{"StarvingHair1DownSickWeak", new List<String>{"WkStBody", "WkStSiDownFace", "WkStHair1" } },
				{"StarvingHair2DownSickWeak", new List<String>{"WkStBody", "WkStSiDownFace", "WkStHair2" } },
				{"StarvingHair3DownSickWeak", new List<String>{"WkStBody", "WkStSiDownFace", "WkStHair3" } },
				{"StarvingHair0NormalHurtWeak", new List<String>{"WkStBody", "WkStFace", "WkStHair0", "WkStHurt" } },
				{"StarvingHair1NormalHurtWeak", new List<String>{"WkStBody", "WkStFace", "WkStHair1", "WkStHurt"  } },
				{"StarvingHair2NormalHurtWeak", new List<String>{"WkStBody", "WkStFace", "WkStHair2", "WkStHurt"  } },
				{"StarvingHair3NormalHurtWeak", new List<String>{"WkStBody", "WkStFace", "WkStHair3", "WkStHurt" } },
				{"StarvingHair0UpHurtWeak", new List<String>{"WkStBody", "WkStUpFace", "WkStHair0","WkStHurt" } },
				{"StarvingHair1UpHurtWeak", new List<String>{"WkStBody", "WkStUpFace", "WkStHair1","WkStHurt" } },
				{"StarvingHair2UpHurtWeak", new List<String>{"WkStBody", "WkStUpFace", "WkStHair2","WkStHurt" } },
				{"StarvingHair3UpHurtWeak", new List<String>{"WkStBody", "WkStUpFace", "WkStHair3","WkStHurt" } },
				{"StarvingHair0DownHurtWeak", new List<String>{"WkStBody", "WkStDownFace", "WkStHair0", "WkStHurt"  } },
				{"StarvingHair1DownHurtWeak", new List<String>{"WkStBody", "WkStDownFace", "WkStHair1", "WkStHurt"  } },
				{"StarvingHair2DownHurtWeak", new List<String>{"WkStBody", "WkStDownFace", "WkStHair2", "WkStHurt"  } },
				{"StarvingHair3DownHurtWeak", new List<String>{"WkStBody", "WkStDownFace", "WkStHair3", "WkStHurt" } },
				{"StarvingHair0NormalHurtSickWeak", new List<String>{"WkStBody", "WkStSiFace", "WkStHair0", "WkStHurt" } },
				{"StarvingHair1NormalHurtSickWeak", new List<String>{"WkStBody", "WkStSiFace", "WkStHair1", "WkStHurt"  } },
				{"StarvingHair2NormalHurtSickWeak", new List<String>{"WkStBody", "WkStSiFace", "WkStHair2", "WkStHurt"  } },
				{"StarvingHair3NormalHurtSickWeak", new List<String>{"WkStBody", "WkStSiFace", "WkStHair3", "WkStHurt" } },
				{"StarvingHair0UpHurtSickWeak", new List<String>{"WkStBody", "WkStSiUpFace", "WkStHair0", "WkStHurt"  } },
				{"StarvingHair1UpHurtSickWeak", new List<String>{"WkStBody", "WkStSiUpFace", "WkStHair1", "WkStHurt"  } },
				{"StarvingHair2UpHurtSickWeak", new List<String>{"WkStBody", "WkStSiUpFace", "WkStHair2", "WkStHurt"  } },
				{"StarvingHair3UpHurtSickWeak", new List<String>{"WkStBody", "WkStSiUpFace", "WkStHair3", "WkStHurt" } },
				{"StarvingHair0DownHurtSickWeak", new List<String>{"WkStBody", "WkStSiDownFace", "WkStHair0", "WkStHurt" } },
				{"StarvingHair1DownHurtSickWeak", new List<String>{"WkStBody", "WkStSiDownFace", "WkStHair1", "WkStHurt"  } },
				{"StarvingHair2DownHurtSickWeak", new List<String>{"WkStBody", "WkStSiDownFace", "WkStHair2", "WkStHurt"  } },
				{"StarvingHair3DownHurtSickWeak", new List<String>{"WkStBody", "WkStSiDownFace", "WkStHair3", "WkStHurt" } },
				//-Insane
				{"NormalHair0Insane",  new List<String>{"InsBody", "InsFace", "InsHair0"}},
				{"NormalHair1Insane",  new List<String>{"InsBody", "InsFace", "InsHair1"}},
				{"NormalHair2Insane",  new List<String>{"InsBody", "InsFace", "InsHair2"}},
				{"NormalHair3Insane",  new List<String>{"InsBody", "InsFace", "InsHair3"}},
				{"NormalHair0InsaneSick",  new List<String>{"InsBody", "InsSiFace", "InsHair0"}},
				{"NormalHair1InsaneSick",  new List<String>{"InsBody", "InsSiFace", "InsHair1"}},
				{"NormalHair2InsaneSick",  new List<String>{"InsBody", "InsSiFace", "InsHair2"}},
				{"NormalHair3InsaneSick",  new List<String>{"InsBody", "InsSiFace", "InsHair3"}},
				{"NormalHair0InsaneHurt",  new List<String>{"InsBody", "InsFace", "InsHair0", "InsHurt"}},
				{"NormalHair1InsaneHurt",  new List<String>{"InsBody", "InsFace", "InsHair1", "InsHurt"}},
				{"NormalHair2InsaneHurt",  new List<String>{"InsBody", "InsFace", "InsHair2", "InsHurt"}},
				{"NormalHair3InsaneHurt",  new List<String>{"InsBody", "InsFace", "InsHair3", "InsHurt"}},
				{"NormalHair0InsaneHurtSick",  new List<String>{"InsBody", "InsSiFace", "InsHair0", "InsHurt"}},
				{"NormalHair1InsaneHurtSick",  new List<String>{"InsBody", "InsSiFace", "InsHair1", "InsHurt"}},
				{"NormalHair2InsaneHurtSick",  new List<String>{"InsBody", "InsSiFace", "InsHair2", "InsHurt"}},
				{"NormalHair3InsaneHurtSick",  new List<String>{"InsBody", "InsSiFace", "InsHair3", "InsHurt"}},
				//-Insane Starving
				{"StarvingHair0Insane",  new List<String>{"InsStBody", "InsStFace", "InsStHair0"}},
				{"StarvingHair1Insane",  new List<String>{"InsStBody", "InsStFace", "InsStHair1"}},
				{"StarvingHair2Insane",  new List<String>{"InsStBody", "InsStFace", "InsStHair2"}},
				{"StarvingHair3Insane",  new List<String>{"InsStBody", "InsStFace", "InsStHair3"}},
				{"StarvingHair0InsaneSick",  new List<String>{"InsStBody", "InsStSiFace", "InsStHair0"}},
				{"StarvingHair1InsaneSick",  new List<String>{"InsStBody", "InsStSiFace", "InsStHair1"}},
				{"StarvingHair2InsaneSick",  new List<String>{"InsStBody", "InsStSiFace", "InsStHair2"}},
				{"StarvingHair3InsaneSick",  new List<String>{"InsStBody", "InsStSiFace", "InsStHair3"}},
				{"StarvingHair0InsaneHurt",  new List<String>{"InsStBody", "InsStFace", "InsStHair0", "InsStHurt"}},
				{"StarvingHair1InsaneHurt",  new List<String>{"InsStBody", "InsStFace", "InsStHair1", "InsStHurt"}},
				{"StarvingHair2InsaneHurt",  new List<String>{"InsStBody", "InsStFace", "InsStHair2", "InsStHurt"}},
				{"StarvingHair3InsaneHurt",  new List<String>{"InsStBody", "InsStFace", "InsStHair3", "InsStHurt"}},
				{"StarvingHair0InsaneHurtSick",  new List<String>{"InsStBody", "InsStSiFace", "InsStHair0", "InsStHurt"}},
				{"StarvingHair1InsaneHurtSick",  new List<String>{"InsStBody", "InsStSiFace", "InsStHair1", "InsStHurt"}},
				{"StarvingHair2InsaneHurtSick",  new List<String>{"InsStBody", "InsStSiFace", "InsStHair2", "InsStHurt"}},
				{"StarvingHair3InsaneHurtSick",  new List<String>{"InsStBody", "InsStSiFace", "InsStHair3", "InsStHurt"}},
				//-Insane WellFed
				{"WellFedHair0Insane",  new List<String>{"InsWFBody", "InsWFFace", "InsWFHair0"}},
				{"WellFedHair1Insane",  new List<String>{"InsWFBody", "InsWFFace", "InsWFHair1"}},
				{"WellFedHair2Insane",  new List<String>{"InsWFBody", "InsWFFace", "InsWFHair2"}},
				{"WellFedHair3Insane",  new List<String>{"InsWFBody", "InsWFFace", "InsWFHair3"}},
				{"WellFedHair0InsaneSick",  new List<String>{"InsWFBody", "InsWFSiFace", "InsWFHair0"}},
				{"WellFedHair1InsaneSick",  new List<String>{"InsWFBody", "InsWFSiFace", "InsWFHair1"}},
				{"WellFedHair2InsaneSick",  new List<String>{"InsWFBody", "InsWFSiFace", "InsWFHair2"}},
				{"WellFedHair3InsaneSick",  new List<String>{"InsWFBody", "InsWFSiFace", "InsWFHair3"}},
				{"WellFedHair0InsaneHurt",  new List<String>{"InsWFBody", "InsWFFace", "InsWFHair0", "InsWFHurt"}},
				{"WellFedHair1InsaneHurt",  new List<String>{"InsWFBody", "InsWFFace", "InsWFHair1", "InsWFHurt"}},
				{"WellFedHair2InsaneHurt",  new List<String>{"InsWFBody", "InsWFFace", "InsWFHair2", "InsWFHurt"}},
				{"WellFedHair3InsaneHurt",  new List<String>{"InsWFBody", "InsWFFace", "InsWFHair3", "InsWFHurt"}},
				{"WellFedHair0InsaneHurtSick",  new List<String>{"InsWFBody", "InsWFSiFace", "InsWFHair0", "InsWFHurt"}},
				{"WellFedHair1InsaneHurtSick",  new List<String>{"InsWFBody", "InsWFSiFace", "InsWFHair1", "InsWFHurt"}},
				{"WellFedHair2InsaneHurtSick",  new List<String>{"InsWFBody", "InsWFSiFace", "InsWFHair2", "InsWFHurt"}},
				{"WellFedHair3InsaneHurtSick",  new List<String>{"InsWFBody", "InsWFSiFace", "InsWFHair3", "InsWFHurt"}},
				//-Insane Weak
				{"NormalHair0InsaneWeak",  new List<String>{"InsWkBody", "InsWkFace", "InsWkHair0"}},
				{"NormalHair1InsaneWeak",  new List<String>{"InsWkBody", "InsWkFace", "InsWkHair1"}},
				{"NormalHair2InsaneWeak",  new List<String>{"InsWkBody", "InsWkFace", "InsWkHair2"}},
				{"NormalHair3InsaneWeak",  new List<String>{"InsWkBody", "InsWkFace", "InsWkHair3"}},
				{"NormalHair0InsaneSickWeak",  new List<String>{"InsWkBody", "InsWkSiFace", "InsWkHair0"}},
				{"NormalHair1InsaneSickWeak",  new List<String>{"InsWkBody", "InsWkSiFace", "InsWkHair1"}},
				{"NormalHair2InsaneSickWeak",  new List<String>{"InsWkBody", "InsWkSiFace", "InsWkHair2"}},
				{"NormalHair3InsaneSickWeak",  new List<String>{"InsWkBody", "InsWkSiFace", "InsWkHair3"}},
				{"NormalHair0InsaneHurtWeak",  new List<String>{"InsWkBody", "InsWkFace", "InsWkHair0", "InsWkHurt"}},
				{"NormalHair1InsaneHurtWeak",  new List<String>{"InsWkBody", "InsWkFace", "InsWkHair1", "InsWkHurt"}},
				{"NormalHair2InsaneHurtWeak",  new List<String>{"InsWkBody", "InsWkFace", "InsWkHair2", "InsWkHurt"}},
				{"NormalHair3InsaneHurtWeak",  new List<String>{"InsWkBody", "InsWkFace", "InsWkHair3", "InsWkHurt"}},
				{"NormalHair0InsaneHurtSickWeak",  new List<String>{"InsWkBody", "InsWkSiFace", "InsWkHair0", "InsWkHurt"}},
				{"NormalHair1InsaneHurtSickWeak",  new List<String>{"InsWkBody", "InsWkSiFace", "InsWkHair1", "InsWkHurt"}},
				{"NormalHair2InsaneHurtSickWeak",  new List<String>{"InsWkBody", "InsWkSiFace", "InsWkHair2", "InsWkHurt"}},
				{"NormalHair3InsaneHurtSickWeak",  new List<String>{"InsWkBody", "InsWkSiFace", "InsWkHair3", "InsWkHurt"}},
				//-Insane Starving Weak
				{"StarvingHair0InsaneWeak",  new List<String>{"InsWkStBody", "InsWkStFace", "InsWkStHair0"}},
				{"StarvingHair1InsaneWeak",  new List<String>{"InsWkStBody", "InsWkStFace", "InsWkStHair1"}},
				{"StarvingHair2InsaneWeak",  new List<String>{"InsWkStBody", "InsWkStFace", "InsWkStHair2"}},
				{"StarvingHair3InsaneWeak",  new List<String>{"InsWkStBody", "InsWkStFace", "InsWkStHair3"}},
				{"StarvingHair0InsaneSickWeak",  new List<String>{"InsWkStBody", "InsWkStSiFace", "InsWkStHair0"}},
				{"StarvingHair1InsaneSickWeak",  new List<String>{"InsWkStBody", "InsWkStSiFace", "InsWkStHair1"}},
				{"StarvingHair2InsaneSickWeak",  new List<String>{"InsWkStBody", "InsWkStSiFace", "InsWkStHair2"}},
				{"StarvingHair3InsaneSickWeak",  new List<String>{"InsWkStBody", "InsWkStSiFace", "InsWkStHair3"}},
				{"StarvingHair0InsaneHurtWeak",  new List<String>{"InsWkStBody", "InsWkStFace", "InsWkStHair0", "InsWkStHurt"}},
				{"StarvingHair1InsaneHurtWeak",  new List<String>{"InsWkStBody", "InsWkStFace", "InsWkStHair1", "InsWkStHurt"}},
				{"StarvingHair2InsaneHurtWeak",  new List<String>{"InsWkStBody", "InsWkStFace", "InsWkStHair2", "InsWkStHurt"}},
				{"StarvingHair3InsaneHurtWeak",  new List<String>{"InsWkStBody", "InsWkStFace", "InsWkStHair3", "InsWkStHurt"}},
				{"StarvingHair0InsaneHurtSickWeak",  new List<String>{"InsWkStBody", "InsWkStSiFace", "InsWkStHair0", "InsWkStHurt"}},
				{"StarvingHair1InsaneHurtSickWeak",  new List<String>{"InsWkStBody", "InsWkStSiFace", "InsWkStHair1", "InsWkStHurt"}},
				{"StarvingHair2InsaneHurtSickWeak",  new List<String>{"InsWkStBody", "InsWkStSiFace", "InsWkStHair2", "InsWkStHurt"}},
				{"StarvingHair3InsaneHurtSickWeak",  new List<String>{"InsWkStBody", "InsWkStSiFace", "InsWkStHair3", "InsWkStHurt"}},
				//-Insane WellFed Weak
				{"WellFedHair0InsaneWeak",  new List<String>{"InsWFWkBody", "InsWFWkFace", "InsWFWkHair0"}},
				{"WellFedHair1InsaneWeak",  new List<String>{"InsWFWkBody", "InsWFWkFace", "InsWFWkHair1"}},
				{"WellFedHair2InsaneWeak",  new List<String>{"InsWFWkBody", "InsWFWkFace", "InsWFWkHair2"}},
				{"WellFedHair3InsaneWeak",  new List<String>{"InsWFWkBody", "InsWFWkFace", "InsWFWkHair3"}},
				{"WellFedHair0InsaneSickWeak",  new List<String>{"InsWFWkBody", "InsWFWkSiFace", "InsWFWkHair0"}},
				{"WellFedHair1InsaneSickWeak",  new List<String>{"InsWFWkBody", "InsWFWkSiFace", "InsWFWkHair1"}},
				{"WellFedHair2InsaneSickWeak",  new List<String>{"InsWFWkBody", "InsWFWkSiFace", "InsWFWkHair2"}},
				{"WellFedHair3InsaneSickWeak",  new List<String>{"InsWFWkBody", "InsWFWkSiFace", "InsWFWkHair3"}},
				{"WellFedHair0InsaneHurtWeak",  new List<String>{"InsWFWkBody", "InsWFWkFace", "InsWFWkHair0", "InsWFWkHurt"}},
				{"WellFedHair1InsaneHurtWeak",  new List<String>{"InsWFWkBody", "InsWFWkFace", "InsWFWkHair1", "InsWFWkHurt"}},
				{"WellFedHair2InsaneHurtWeak",  new List<String>{"InsWFWkBody", "InsWFWkFace", "InsWFWkHair2", "InsWFWkHurt"}},
				{"WellFedHair3InsaneHurtWeak",  new List<String>{"InsWFWkBody", "InsWFWkFace", "InsWFWkHair3", "InsWFWkHurt"}},
				{"WellFedHair0InsaneHurtSickWeak",  new List<String>{"InsWFWkBody", "InsWFWkSiFace", "InsWFWkHair0", "InsWFWkHurt"}},
				{"WellFedHair1InsaneHurtSickWeak",  new List<String>{"InsWFWkBody", "InsWFWkSiFace", "InsWFWkHair1", "InsWFWkHurt"}},
				{"WellFedHair2InsaneHurtSickWeak",  new List<String>{"InsWFWkBody", "InsWFWkSiFace", "InsWFWkHair2", "InsWFWkHurt"}},
				{"WellFedHair3InsaneHurtSickWeak",  new List<String>{"InsWFWkBody", "InsWFWkSiFace", "InsWFWkHair3", "InsWFWkHurt"}},
				//-Specials
				{"DeadHair0",  new List<String>{"DeadBody", "DeadHair0"}},
				{"DeadHair1",  new List<String>{"DeadBody", "DeadHair1"}},
				{"DeadHair2",  new List<String>{"DeadBody", "DeadHair2"}},
				{"DeadHair3",  new List<String>{"DeadBody", "DeadHair3"}},
				{"AlienHair0",  new List<String>{"AlienBody", "AlienHair0"}},
				{"AlienHair1",  new List<String>{"AlienBody", "AlienHair1"}},
				{"AlienHair2",  new List<String>{"AlienBody", "AlienHair2"}},
				{"AlienHair3",  new List<String>{"AlienBody", "AlienHair3"}},
				{"AndroidHair0",  new List<String>{"AndrBody", "AndrHair0"}},
				{"AndroidHair1",  new List<String>{"AndrBody", "AndrHair1"}},
				{"AndroidHair2",  new List<String>{"AndrBody", "AndrHair2"}},
				{"AndroidHair3",  new List<String>{"AndrBody", "AndrHair3"}},
				{"Communist",  new List<String>{ "CommBody", "Ushanka"}}
			};
	}
}
